/**
 * Provider connector I/O types for @primis/workers.
 *
 * These types define the inputs and outputs for each method on `HealthProviderConnector`.
 * They are deliberately provider-agnostic — no Google Health, HealthKit, or Health Connect
 * specifics appear here.
 *
 * Design notes:
 *   - `TokenExchangeResult` uses `*Ref` suffixes on all token fields. These fields store
 *     AWS Secrets Manager ARN references ONLY, never raw OAuth token values.
 *     See ADR-001, migration 000003, and TAD §22 (security / token handling).
 *   - `RawProviderPayload.data` is typed as `unknown` because the provider-native payload
 *     shape varies by connector. The archive layer (CU-036) serialises and redacts before
 *     writing to S3; normalizers (CU-041–043) decode with provider-specific schemas.
 *   - `ProviderSyncResult` mirrors the `provider_sync_jobs` counters so callers can write
 *     the result directly to the DB row without mapping.
 */

import type { ProviderCode, SyncJobStatus } from '@primis/core-types';

// ---------------------------------------------------------------------------
// OAuth / authorization types
// ---------------------------------------------------------------------------

/**
 * Returned by `HealthProviderConnector.startAuthorization()`.
 *
 * `state` is a CSRF-protection nonce that must be stored by the caller and
 * verified when the provider redirects back with the authorization code.
 */
export interface AuthStartResult {
  /** The URL to redirect the user to for provider OAuth consent. */
  authorizeUrl: string;

  /**
   * Opaque CSRF nonce generated by the connector.
   * The caller must persist this and verify it matches the `state` param returned
   * by the provider's redirect to the callback URI.
   */
  state: string;
}

/**
 * Parameters extracted from the provider's OAuth callback redirect URI.
 * Passed to `HealthProviderConnector.completeAuthorization()`.
 */
export interface OAuthCallbackParams {
  /** Authorization code returned by the provider. Single-use, short-lived. */
  code: string;

  /** CSRF nonce from the provider redirect; must match the value in `AuthStartResult.state`. */
  state: string;

  /** The redirect URI that was registered with the provider and used in the auth request. */
  redirectUri: string;
}

/**
 * Returned by `HealthProviderConnector.completeAuthorization()` after a successful
 * authorization code exchange.
 *
 * IMPORTANT: `accessTokenRef` and `refreshTokenRef` are AWS Secrets Manager ARN
 * reference strings, NOT raw token values. The token secret adapter (CU-038) is
 * responsible for storing the real tokens in Secrets Manager and returning the ARNs.
 * In local dev these values may be placeholder strings.
 */
export interface TokenExchangeResult {
  /**
   * AWS Secrets Manager ARN reference for the stored access token.
   * Example: `arn:aws:secretsmanager:us-east-1:123456789:secret:primis/prod/google/access/abc`
   * In local dev: a placeholder string (never a real token value).
   */
  accessTokenRef: string;

  /**
   * AWS Secrets Manager ARN reference for the stored refresh token.
   * Example: `arn:aws:secretsmanager:us-east-1:123456789:secret:primis/prod/google/refresh/abc`
   * In local dev: a placeholder string (never a real token value).
   */
  refreshTokenRef: string;

  /**
   * UTC expiry of the access token as reported by the provider.
   * `null` if the provider does not communicate an expiry (e.g. long-lived tokens).
   */
  expiresAt: Date | null;

  /**
   * OAuth scopes actually granted by the user during the authorization flow.
   * May be a subset of the requested scopes if the user declined some permissions.
   */
  scopesGranted: string[];

  /**
   * Provider-assigned account identifier for the authenticated user (e.g. Google `sub` claim).
   * Stored in `provider_connections.external_account_id` for deduplication.
   */
  externalAccountId: string;
}

// ---------------------------------------------------------------------------
// Sync result types
// ---------------------------------------------------------------------------

/**
 * A single error that occurred during a `syncWindow` invocation.
 *
 * Non-fatal errors are collected and returned in `ProviderSyncResult.errors` so
 * that a partial sync can still succeed. Fatal errors should throw `ProviderConnectorError`.
 */
export interface ProviderSyncError {
  /**
   * Machine-readable error code.
   * Use `SCREAMING_SNAKE_CASE` strings matching the provider's own error taxonomy
   * or Primis internal codes (e.g. `'RATE_LIMITED'`, `'PERMISSION_DENIED'`,
   * `'NORMALIZATION_FAILED'`).
   */
  code: string;

  /** Human-readable description of the error for logging and debugging. */
  message: string;

  /**
   * The provider data type that produced this error (e.g. `'daily-resting-heart-rate'`).
   * Omit when the error applies to the sync as a whole rather than a specific data type.
   */
  dataType?: string;
}

/**
 * Summary result returned by `HealthProviderConnector.syncWindow()`.
 *
 * Counter fields mirror the corresponding columns in `provider_sync_jobs` so the
 * sync runner (CU-045) can update the job row directly from this result.
 */
export interface ProviderSyncResult {
  /**
   * The `provider_sync_jobs.id` of the job row created by the sync runner for this window.
   * The connector receives this from the caller to correlate archive metadata (CU-044).
   */
  jobId: string;

  /** Total number of raw records fetched from the provider API. */
  recordsFetched: number;

  /** Number of raw records successfully normalized into canonical observations. */
  recordsNormalized: number;

  /** Number of raw payloads written to the local or S3 archive. */
  payloadsArchived: number;

  /**
   * Terminal status of this sync window.
   * `'succeeded'` — all records normalized; `'partial_success'` — some errors in `errors`;
   * `'failed'` — the window could not be completed.
   */
  status: SyncJobStatus;

  /**
   * Non-fatal errors encountered during this window.
   * An empty array indicates a fully clean sync.
   * Non-empty arrays with `status: 'partial_success'` indicate best-effort partial data.
   */
  errors: ProviderSyncError[];
}

// ---------------------------------------------------------------------------
// Raw payload envelope
// ---------------------------------------------------------------------------

/**
 * Envelope wrapping a single raw provider API response before archiving and normalization.
 *
 * `data` is typed as `unknown` intentionally — each connector's archive step serialises
 * the raw response with the correct provider-specific shape. Normalizers cast `data` using
 * provider-specific Zod schemas or type guards, not this generic type.
 *
 * IMPORTANT: Never commit a `RawProviderPayload` with real user data to version control.
 * Run `scripts/redact-fixture.ts` on any fixtures before committing.
 */
export interface RawProviderPayload {
  /**
   * Canonical provider code per ADR-001.
   */
  providerCode: ProviderCode;

  /**
   * Provider-native data type identifier (e.g. `'daily-heart-rate-variability'`,
   * `'sleep'`, `'workouts'`). Must match the value used in `provider_data_availability`
   * and `raw_provider_payloads` rows.
   */
  dataType: string;

  /** The raw API response body. Shape is provider and data-type specific. */
  data: unknown;

  /** UTC timestamp when this payload was fetched from the provider API. */
  fetchedAt: Date;

  /** Start of the data window covered by this payload (UTC, inclusive). */
  windowStart: Date;

  /** End of the data window covered by this payload (UTC, exclusive). */
  windowEnd: Date;
}
