/**
 * Kysely `Database` interface — the central registry of all typed table definitions.
 *
 * Each schema CU adds table interfaces here:
 *   - CU-027: identity, preferences, consent tables
 *   - CU-028: provider connection and sync tables
 *   - CU-029: metric registry and observation tables
 *   - CU-030: domain tables (sleep, activity, body composition, manual inputs, nutrition)
 *   - CU-031: score, insight, AI, and dashboard tables
 *
 * The `Database` interface is intentionally maintained by hand rather than generated
 * by a tool like `kysely-codegen`. The SQL migration files in `database/migrations/`
 * are the canonical schema source. Types here must accurately reflect those files.
 * See ADR-003 for the rationale.
 *
 * Internal-use table: `schema_migrations` is tracked here as a `SchemaMigrationsTable`
 * so the migration runner can query it in a type-safe manner.
 *
 * Column type conventions used throughout this file:
 *   - `Generated<T>`     — column has a DB default; T is required on SELECT,
 *                          optional on INSERT, and T on UPDATE. Imported from kysely.
 *   - `UuidPk`           — UUID primary key with gen_random_uuid() default;
 *                          optional on INSERT, never updated.
 *   - `CreatedAt`        — timestamptz with now() default; optional on INSERT,
 *                          immutable after creation (never update).
 *   - `UpdatedAt`        — timestamptz with now() default; optional on INSERT,
 *                          set explicitly by repository write methods (D-A-008).
 *   - `NullableCol<T>`   — nullable column; T | null on SELECT and UPDATE,
 *                          optional (T | null | undefined) on INSERT.
 *
 * Note on `exactOptionalPropertyTypes: true`:
 *   Kysely's `Insertable<T>` and `Updateable<T>` helpers generate correct optional
 *   property types. Repositories should use `Insertable<XTable>` and `Updateable<XTable>`
 *   rather than hand-writing `field?: T | undefined` in function signatures.
 */

import type { ColumnType, Generated, Selectable, Insertable, Updateable } from 'kysely';

// ---------------------------------------------------------------------------
// Shared column-type aliases
// ---------------------------------------------------------------------------

/** UUID primary key with `gen_random_uuid()` default. Never updated. */
type UuidPk = ColumnType<string, string | undefined, never>;

/** `created_at timestamptz not null default now()` — immutable after creation. */
type CreatedAt = ColumnType<Date, Date | undefined, never>;

/**
 * `updated_at timestamptz not null default now()` — set explicitly by
 * repository write methods on every mutation (D-A-008, no DB trigger).
 */
type UpdatedAt = Generated<Date>;

/**
 * Nullable column that may be omitted on INSERT (becomes NULL in the DB).
 * Maps to `T | null` on SELECT/UPDATE and `T | null | undefined` on INSERT
 * so Kysely's `Insertable<T>` renders the field as optional.
 */
type NullableCol<T> = ColumnType<T | null, T | null | undefined, T | null>;

// ---------------------------------------------------------------------------
// schema_migrations (migration tracking — 000001_init.sql)
// ---------------------------------------------------------------------------

/**
 * Row shape for the `schema_migrations` tracking table.
 * Managed exclusively by the migration runner — not exposed via repositories.
 */
export interface SchemaMigrationsTable {
  /** Filename stem of the applied migration, e.g. '000001_init'. */
  version: string;
  /** Timestamp when the migration was applied; DB-generated default. */
  applied_at: ColumnType<Date, never, never>;
}

/** Selectable row type for `schema_migrations`. */
export type SchemaMigration = Selectable<SchemaMigrationsTable>;

/** Insertable row type for `schema_migrations`. */
export type NewSchemaMigration = Insertable<SchemaMigrationsTable>;

// ---------------------------------------------------------------------------
// users (000002_identity_preferences.sql — §7.1)
// ---------------------------------------------------------------------------

/**
 * Core application identity.
 *
 * Key design points:
 *   - `id` is the internal UUID — the primary key for all health-data FK references
 *     (ARCH-AUTH-001). Never expose `id` directly to clients.
 *   - `cognito_sub` is stored as a separate unique text field. It is the lookup key
 *     used by the auth middleware to resolve internal user identity (ARCH-AUTH-002).
 *   - `sex_at_birth`, `date_of_birth`, and `height_cm` are optional user-controlled
 *     biometrics. Never infer or require these.
 */
export interface UsersTable {
  /** Internal UUID primary key; generated by `gen_random_uuid()`. */
  id: UuidPk;
  /** Cognito `sub` claim from the user's ID token. Unique across all users. */
  cognito_sub: string;
  /** Primary email address; null until verified or provided during sign-up. */
  email: NullableCol<string>;
  /** Whether the email address has been verified via Cognito. */
  email_verified: Generated<boolean>;
  /** Display name shown in the app. */
  display_name: NullableCol<string>;
  /**
   * Account lifecycle status.
   * Allowed values: 'active' | 'suspended' | 'deletion_requested' | 'deleted'
   */
  status: Generated<string>;
  /** IANA timezone string for the user's primary local zone, e.g. 'America/New_York'. */
  primary_timezone: Generated<string>;
  /**
   * Date of birth in ISO format (YYYY-MM-DD), returned as string by node-postgres.
   * Optional; do not require or infer.
   */
  date_of_birth: NullableCol<string>;
  /**
   * Biological sex at birth — user-controlled, optional.
   * Do not infer demographic data.
   */
  sex_at_birth: NullableCol<string>;
  /**
   * Height in centimetres (numeric(6,2)); returned as string by node-postgres.
   * Optional; used to improve VO2/body-composition interpretation.
   */
  height_cm: NullableCol<string>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  /** Set when user requests deletion; null for active accounts. */
  deleted_at: NullableCol<Date>;
}

/** Full row shape returned by SELECT queries on `users`. */
export type User = Selectable<UsersTable>;
/** Shape accepted by INSERT queries on `users`. */
export type NewUser = Insertable<UsersTable>;
/** Shape accepted by UPDATE queries on `users`. */
export type UserUpdate = Updateable<UsersTable>;

// ---------------------------------------------------------------------------
// auth_identities (000002_identity_preferences.sql — §7.2)
// ---------------------------------------------------------------------------

/**
 * Links sign-in methods to a Primis user account.
 *
 * IMPORTANT: `provider` values represent app authentication methods only.
 * Allowed: 'email_password' | 'google' | 'apple' | 'facebook'
 *
 * 'google' here means signing into Primis with a Google account (OAuth sign-in).
 * It is NOT the same as Google Health API authorization, which is tracked in
 * `provider_connections` (CU-028). See TAD §9.2.
 */
export interface AuthIdentitiesTable {
  /** Internal UUID primary key. */
  id: UuidPk;
  /** FK to `users.id`. */
  user_id: string;
  /**
   * App sign-in method.
   * Allowed values: 'email_password' | 'google' | 'apple' | 'facebook'
   */
  provider: string;
  /** Provider-assigned subject identifier (e.g. Google sub claim). */
  provider_subject: string;
  /** Email associated with this identity (may differ from users.email). */
  email: NullableCol<string>;
  linked_at: CreatedAt;
  /** Null until the user has authenticated via this identity at least once. */
  last_used_at: NullableCol<Date>;
}

/** Full row shape returned by SELECT queries on `auth_identities`. */
export type AuthIdentity = Selectable<AuthIdentitiesTable>;
/** Shape accepted by INSERT queries on `auth_identities`. */
export type NewAuthIdentity = Insertable<AuthIdentitiesTable>;
/** Shape accepted by UPDATE queries on `auth_identities`. */
export type AuthIdentityUpdate = Updateable<AuthIdentitiesTable>;

// ---------------------------------------------------------------------------
// user_goals (000002_identity_preferences.sql — §7.3)
// ---------------------------------------------------------------------------

/**
 * Ranked product goals selected during onboarding.
 *
 * `goal_code` values are application-level enums validated by Zod (D-A-009).
 * No DB CHECK constraint so the list can extend without a migration.
 * Current values: 'athletic_performance' | 'sleep' | 'body_composition' |
 *   'fat_loss' | 'muscle_gain' | 'longevity' | 'general_health'
 */
export interface UserGoalsTable {
  /** Internal UUID primary key. */
  id: UuidPk;
  /** FK to `users.id`. */
  user_id: string;
  /**
   * Goal identifier. Application-level enum; see GoalCode in api-contracts (CU-033).
   */
  goal_code: string;
  /** Ordering rank (1 = highest priority). */
  priority_rank: number;
  is_active: Generated<boolean>;
  /** Free-form extension data. */
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

/** Full row shape returned by SELECT queries on `user_goals`. */
export type UserGoal = Selectable<UserGoalsTable>;
/** Shape accepted by INSERT queries on `user_goals`. */
export type NewUserGoal = Insertable<UserGoalsTable>;
/** Shape accepted by UPDATE queries on `user_goals`. */
export type UserGoalUpdate = Updateable<UserGoalsTable>;

// ---------------------------------------------------------------------------
// coach_preferences (000002_identity_preferences.sql — §7.4)
// ---------------------------------------------------------------------------

/**
 * Coach tone and summary style preferences.
 * One row per user; `user_id` is both the primary key and FK to `users`.
 *
 * Allowed coach_style values:
 *   'analyst_coach' | 'strict' | 'encouraging' | 'performance_coach' |
 *   'calm' | 'concise' | 'explanatory' | 'unhinged_lite'
 */
export interface CoachPreferencesTable {
  /** PK and FK to `users.id` (1-to-1 relationship). */
  user_id: string;
  /**
   * Overall coaching persona.
   * Allowed values enforced by DB CHECK constraint.
   */
  coach_style: Generated<string>;
  /** Summary tone. */
  summary_style: Generated<string>;
  /**
   * Level of explanation detail.
   * Allowed: 'concise' | 'balanced' | 'detailed' | 'data_heavy'
   */
  explanation_depth: Generated<string>;
  /**
   * Push frequency/firmness.
   * Allowed: 'gentle' | 'moderate' | 'strict'
   */
  coaching_intensity: Generated<string>;
  /**
   * Humor tone.
   * Allowed: 'none' | 'low' | 'medium'
   */
  humor_level: Generated<string>;
  /** Enables the 'unhinged_lite' coach persona when true. */
  allow_unhinged_lite: Generated<boolean>;
  updated_at: UpdatedAt;
}

/** Full row shape returned by SELECT queries on `coach_preferences`. */
export type CoachPreferences = Selectable<CoachPreferencesTable>;
/** Shape accepted by INSERT queries on `coach_preferences`. */
export type NewCoachPreferences = Insertable<CoachPreferencesTable>;
/** Shape accepted by UPDATE queries on `coach_preferences`. */
export type CoachPreferencesUpdate = Updateable<CoachPreferencesTable>;

// ---------------------------------------------------------------------------
// nutrition_philosophy_preferences (000002_identity_preferences.sql — §7.5)
// ---------------------------------------------------------------------------

/**
 * User-selectable nutrition leanings.
 * One row per user; `user_id` is both the primary key and FK to `users`.
 *
 * Defaults reflect a whole-foods, high-protein, anti-inflammatory baseline.
 * All flags are freely overridable by the user.
 */
export interface NutritionPhilosophyPreferencesTable {
  /** PK and FK to `users.id` (1-to-1 relationship). */
  user_id: string;
  whole_foods_emphasis: Generated<boolean>;
  high_protein_emphasis: Generated<boolean>;
  animal_product_positive: Generated<boolean>;
  avoid_seed_oils: Generated<boolean>;
  avoid_artificial_dyes: Generated<boolean>;
  avoid_ultra_processed_foods: Generated<boolean>;
  anti_inflammatory_emphasis: Generated<boolean>;
  /** Free-text notes for custom nutrition constraints or preferences. */
  custom_notes: NullableCol<string>;
  updated_at: UpdatedAt;
}

/** Full row shape returned by SELECT queries on `nutrition_philosophy_preferences`. */
export type NutritionPhilosophyPreferences = Selectable<NutritionPhilosophyPreferencesTable>;
/** Shape accepted by INSERT queries on `nutrition_philosophy_preferences`. */
export type NewNutritionPhilosophyPreferences = Insertable<NutritionPhilosophyPreferencesTable>;
/** Shape accepted by UPDATE queries on `nutrition_philosophy_preferences`. */
export type NutritionPhilosophyPreferencesUpdate = Updateable<NutritionPhilosophyPreferencesTable>;

// ---------------------------------------------------------------------------
// consent_records (000002_identity_preferences.sql — §7.6)
// ---------------------------------------------------------------------------

/**
 * Append-only log of meaningful consent events.
 *
 * Allowed consent_type values:
 *   'terms' | 'privacy_policy' | 'ai_processing' | 'google_health' |
 *   'healthkit' | 'health_connect' | 'data_retention' | 'marketing'
 *
 * Note: `ip_hash` and `user_agent_hash` are hashed client metadata for audit
 * purposes. Raw IP addresses and user-agent strings must never be stored.
 */
export interface ConsentRecordsTable {
  /** Internal UUID primary key. */
  id: UuidPk;
  /** FK to `users.id`. */
  user_id: string;
  /**
   * Type of consent event. Enforced by DB CHECK constraint.
   */
  consent_type: string;
  /** Policy or document version the user consented to, e.g. '1.0'. */
  version: string;
  /** True if consent was granted; false if declined or revoked. */
  granted: boolean;
  granted_at: CreatedAt;
  /** Set when consent is revoked after having been granted. */
  revoked_at: NullableCol<Date>;
  /** SHA-256 hash of the client IP address (for audit; never the raw IP). */
  ip_hash: NullableCol<string>;
  /** SHA-256 hash of the User-Agent header (for audit; never the raw value). */
  user_agent_hash: NullableCol<string>;
  /** Free-form audit metadata. */
  metadata: Generated<Record<string, unknown>>;
}

/** Full row shape returned by SELECT queries on `consent_records`. */
export type ConsentRecord = Selectable<ConsentRecordsTable>;
/** Shape accepted by INSERT queries on `consent_records`. */
export type NewConsentRecord = Insertable<ConsentRecordsTable>;

// ---------------------------------------------------------------------------
// data_retention_preferences (000002_identity_preferences.sql — §7.7)
// ---------------------------------------------------------------------------

/**
 * Per-user data retention configuration.
 * One row per user; `user_id` is both the primary key and FK to `users`.
 *
 * raw_payload_retention_mode / ai_context_retention_mode allowed values:
 *   'extended' | 'standard' | 'minimal'
 */
export interface DataRetentionPreferencesTable {
  /** PK and FK to `users.id` (1-to-1 relationship). */
  user_id: string;
  /**
   * Raw provider payload retention policy.
   * Allowed: 'extended' | 'standard' | 'minimal'
   */
  raw_payload_retention_mode: Generated<string>;
  /**
   * Explicit retention window in days; null means policy-based (mode-driven).
   */
  raw_payload_retention_days: NullableCol<number>;
  /** Normalized/relational data retention policy. Default 'keep_until_deleted'. */
  normalized_data_retention_mode: Generated<string>;
  /**
   * AI context/snapshot retention policy.
   * Allowed: 'extended' | 'standard' | 'minimal'
   */
  ai_context_retention_mode: Generated<string>;
  /** Whether the algorithm engine may reprocess this user's data. */
  allow_algorithm_reprocessing: Generated<boolean>;
  updated_at: UpdatedAt;
}

/** Full row shape returned by SELECT queries on `data_retention_preferences`. */
export type DataRetentionPreferences = Selectable<DataRetentionPreferencesTable>;
/** Shape accepted by INSERT queries on `data_retention_preferences`. */
export type NewDataRetentionPreferences = Insertable<DataRetentionPreferencesTable>;
/** Shape accepted by UPDATE queries on `data_retention_preferences`. */
export type DataRetentionPreferencesUpdate = Updateable<DataRetentionPreferencesTable>;

// ---------------------------------------------------------------------------
// provider_connections (000003_provider_sync.sql — §8.2)
// ---------------------------------------------------------------------------

/**
 * A user-authorized integration with a health data provider.
 *
 * SECURITY CRITICAL:
 *   `access_token_secret_ref` and `refresh_token_secret_ref` store AWS Secrets Manager
 *   ARN reference strings ONLY — never raw OAuth tokens. In local dev these are NULL.
 *   ARN format: arn:aws:secretsmanager:{region}:{account}:secret:{path}
 *
 * Provider codes are validated by a DB CHECK constraint against ADR-001 canonical values.
 */
export interface ProviderConnectionsTable {
  /** Internal UUID primary key. */
  id: UuidPk;
  /** FK to `users.id`. */
  user_id: string;
  /**
   * Canonical provider code per ADR-001.
   * Allowed: 'google_health' | 'healthkit' | 'health_connect' |
   *   'hume_via_healthkit' | 'hume_direct_unverified' |
   *   'fooddata_central' | 'manual' | 'primis_internal'
   */
  provider_code: string;
  /**
   * Connection lifecycle status.
   * Allowed: 'active' | 'needs_reauth' | 'revoked' | 'error' | 'disabled'
   */
  connection_status: Generated<string>;
  /** Provider-assigned account identifier (e.g. Google account sub). */
  external_account_id: NullableCol<string>;
  /** Human-readable label for this connection (e.g. "Evan's Fitbit"). */
  display_name: NullableCol<string>;
  /** OAuth scopes actually granted by the user. */
  scopes_granted: Generated<string[]>;
  /** OAuth scopes requested at authorization time. */
  scopes_requested: Generated<string[]>;
  /**
   * AWS Secrets Manager ARN reference for the access token.
   * NEVER a raw token value. NULL in local dev.
   */
  access_token_secret_ref: NullableCol<string>;
  /**
   * AWS Secrets Manager ARN reference for the refresh token.
   * NEVER a raw token value. NULL in local dev.
   */
  refresh_token_secret_ref: NullableCol<string>;
  /** UTC expiry of the access token (if known). */
  token_expires_at: NullableCol<Date>;
  /** Timestamp of the most recent successful sync for this connection. */
  last_successful_sync_at: NullableCol<Date>;
  /** Timestamp of the most recent failed sync for this connection. */
  last_failed_sync_at: NullableCol<Date>;
  /** Machine-readable error code from the last failure, if any. */
  last_error_code: NullableCol<string>;
  /** Human-readable error message from the last failure, if any. */
  last_error_message: NullableCol<string>;
  /** Free-form extension metadata. */
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  /** Set when the connection is soft-deleted. */
  deleted_at: NullableCol<Date>;
}

/** Full row shape returned by SELECT queries on `provider_connections`. */
export type ProviderConnection = Selectable<ProviderConnectionsTable>;
/** Shape accepted by INSERT queries on `provider_connections`. */
export type NewProviderConnection = Insertable<ProviderConnectionsTable>;
/** Shape accepted by UPDATE queries on `provider_connections`. */
export type ProviderConnectionUpdate = Updateable<ProviderConnectionsTable>;

// ---------------------------------------------------------------------------
// provider_data_availability (000003_provider_sync.sql — §8.3)
// ---------------------------------------------------------------------------

/**
 * Tracks whether a specific provider data type is confirmed available for a user.
 *
 * One row per `(user_id, provider_code, provider_data_type, canonical_metric_code)`.
 * Note: the unique constraint uses SQL NULL semantics — two NULLs in
 * `canonical_metric_code` are treated as distinct, so rows with a NULL
 * canonical_metric_code will not conflict with each other.
 */
export interface ProviderDataAvailabilityTable {
  /** Internal UUID primary key. */
  id: UuidPk;
  /** FK to `users.id`. */
  user_id: string;
  /** FK to `provider_connections.id`; nullable for provider-wide entries. */
  provider_connection_id: NullableCol<string>;
  /** Canonical provider code per ADR-001. */
  provider_code: string;
  /** Provider-native data type identifier (e.g. 'daily-heart-rate-variability'). */
  provider_data_type: string;
  /** Resolved canonical metric code from `metric_definitions`; null if unknown. */
  canonical_metric_code: NullableCol<string>;
  /**
   * Availability status.
   * Allowed: 'available' | 'unavailable' | 'permission_missing' |
   *   'no_data_yet' | 'provider_unverified' | 'deprecated' | 'error'
   */
  status: string;
  /** UTC timestamp when data was first seen for this type. */
  first_available_at: NullableCol<Date>;
  /** UTC timestamp of the most recent record seen for this type. */
  last_seen_at: NullableCol<Date>;
  /**
   * Count of records observed so far.
   * bigint in Postgres; node-postgres returns bigint columns as strings
   * to avoid JavaScript precision loss on values exceeding Number.MAX_SAFE_INTEGER.
   */
  sample_count: ColumnType<string, number | string | undefined, number | string>;
  /** Machine-readable error code if status is 'error'. */
  last_error_code: NullableCol<string>;
  /** Human-readable notes about this availability entry. */
  notes: NullableCol<string>;
  /** Free-form extension metadata. */
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

/** Full row shape returned by SELECT queries on `provider_data_availability`. */
export type ProviderDataAvailability = Selectable<ProviderDataAvailabilityTable>;
/** Shape accepted by INSERT queries on `provider_data_availability`. */
export type NewProviderDataAvailability = Insertable<ProviderDataAvailabilityTable>;
/** Shape accepted by UPDATE queries on `provider_data_availability`. */
export type ProviderDataAvailabilityUpdate = Updateable<ProviderDataAvailabilityTable>;

// ---------------------------------------------------------------------------
// provider_metric_mappings (000003_provider_sync.sql — §8.4)
// ---------------------------------------------------------------------------

/**
 * Static or semi-static mapping from a provider data type to a canonical metric code.
 *
 * Seeded with 15 documented Google Health API mappings (verification_status = 'unverified').
 * Only change verification_status to 'verified' after Phase AA live-payload validation.
 */
export interface ProviderMetricMappingsTable {
  /** Internal UUID primary key. */
  id: UuidPk;
  /** Canonical provider code per ADR-001. */
  provider_code: string;
  /** Provider-native data type identifier (e.g. 'daily-resting-heart-rate'). */
  provider_data_type: string;
  /** Canonical metric code from `metric_definitions`. */
  canonical_metric_code: string;
  /** Canonical storage unit (e.g. 'bpm', 'seconds', 'kcal'). */
  canonical_unit: string;
  /** Optional JSON mapping rules for value translation. */
  value_mapping: Generated<Record<string, unknown>>;
  /** Whether this mapping is currently in use for normalization. */
  is_active: Generated<boolean>;
  /**
   * Mapping verification state.
   * Allowed: 'verified' | 'unverified' | 'deprecated'
   */
  verification_status: Generated<string>;
  /** Human-readable notes about this mapping. */
  notes: NullableCol<string>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

/** Full row shape returned by SELECT queries on `provider_metric_mappings`. */
export type ProviderMetricMapping = Selectable<ProviderMetricMappingsTable>;
/** Shape accepted by INSERT queries on `provider_metric_mappings`. */
export type NewProviderMetricMapping = Insertable<ProviderMetricMappingsTable>;
/** Shape accepted by UPDATE queries on `provider_metric_mappings`. */
export type ProviderMetricMappingUpdate = Updateable<ProviderMetricMappingsTable>;

// ---------------------------------------------------------------------------
// provider_sync_jobs (000003_provider_sync.sql — §8.5)
// ---------------------------------------------------------------------------

/**
 * Tracks individual provider sync attempts.
 *
 * Append-only: create a new row for each retry rather than mutating a completed job.
 * Status lifecycle: queued → running → succeeded | partial_success | failed | cancelled
 * No `updated_at` column — status transitions are tracked via started_at / finished_at.
 */
export interface ProviderSyncJobsTable {
  /** Internal UUID primary key. */
  id: UuidPk;
  /** FK to `users.id`. */
  user_id: string;
  /** FK to `provider_connections.id`. */
  provider_connection_id: string;
  /**
   * Sync job category.
   * Allowed: 'initial_backfill' | 'incremental' | 'manual_refresh' |
   *   'webhook' | 'reprocess'
   */
  job_type: string;
  /**
   * Current job status.
   * Allowed: 'queued' | 'running' | 'succeeded' | 'partial_success' |
   *   'failed' | 'cancelled'
   */
  status: string;
  /** Start of the data window being synced (UTC). */
  sync_window_start_utc: NullableCol<Date>;
  /** End of the data window being synced (UTC). */
  sync_window_end_utc: NullableCol<Date>;
  /** UTC timestamp when the job started processing. */
  started_at: NullableCol<Date>;
  /** UTC timestamp when the job completed (any terminal state). */
  finished_at: NullableCol<Date>;
  /** Number of raw records fetched from the provider. */
  records_fetched: Generated<number>;
  /** Number of records successfully normalized into observations. */
  records_normalized: Generated<number>;
  /** Number of raw payloads archived to S3. */
  payloads_archived: Generated<number>;
  /** Machine-readable error code if status is 'failed' or 'partial_success'. */
  error_code: NullableCol<string>;
  /** Human-readable error message for failed jobs. */
  error_message: NullableCol<string>;
  /** Number of retry attempts for this job. */
  retry_count: Generated<number>;
  /** Correlation UUID for distributed tracing across sync pipeline stages. */
  correlation_id: NullableCol<string>;
  /** Free-form extension metadata. */
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
}

/** Full row shape returned by SELECT queries on `provider_sync_jobs`. */
export type ProviderSyncJob = Selectable<ProviderSyncJobsTable>;
/** Shape accepted by INSERT queries on `provider_sync_jobs`. */
export type NewProviderSyncJob = Insertable<ProviderSyncJobsTable>;
/** Shape accepted by UPDATE queries on `provider_sync_jobs`. */
export type ProviderSyncJobUpdate = Updateable<ProviderSyncJobsTable>;

// ---------------------------------------------------------------------------
// provider_sync_cursors (000003_provider_sync.sql — §8.6)
// ---------------------------------------------------------------------------

/**
 * Stores the sync position (watermark) for each connection + data type pair.
 *
 * Enables idempotent incremental syncs: each sync run reads the cursor, fetches
 * records after the high watermark, then upserts the cursor with the new position.
 * One row per `(provider_connection_id, provider_data_type)` — enforced by unique constraint.
 */
export interface ProviderSyncCursorsTable {
  /** Internal UUID primary key. */
  id: UuidPk;
  /** FK to `provider_connections.id`. */
  provider_connection_id: string;
  /** Provider-native data type identifier this cursor applies to. */
  provider_data_type: string;
  /**
   * Provider-specific pagination or sync cursor value (opaque string).
   * Interpretation varies by provider API.
   */
  cursor_value: NullableCol<string>;
  /** Start of the last successfully synced window (UTC). */
  last_synced_start_utc: NullableCol<Date>;
  /** End of the last successfully synced window (UTC). */
  last_synced_end_utc: NullableCol<Date>;
  /** The latest data timestamp confirmed as synced (UTC). */
  high_watermark_utc: NullableCol<Date>;
  /** Free-form extension metadata. */
  metadata: Generated<Record<string, unknown>>;
  updated_at: UpdatedAt;
}

/** Full row shape returned by SELECT queries on `provider_sync_cursors`. */
export type ProviderSyncCursor = Selectable<ProviderSyncCursorsTable>;
/** Shape accepted by INSERT queries on `provider_sync_cursors`. */
export type NewProviderSyncCursor = Insertable<ProviderSyncCursorsTable>;
/** Shape accepted by UPDATE queries on `provider_sync_cursors`. */
export type ProviderSyncCursorUpdate = Updateable<ProviderSyncCursorsTable>;

// ---------------------------------------------------------------------------
// raw_provider_payloads (000003_provider_sync.sql — §8.7)
// ---------------------------------------------------------------------------

/**
 * Metadata for raw provider payloads archived to S3.
 *
 * NO raw payload JSON is written to the database. This table stores only the
 * S3 object reference (bucket + key), content hash, and envelope metadata.
 *
 * S3 key convention (Data Model §8.7):
 *   s3://primis-raw-health-data/{env}/user_id={id}/provider={code}/
 *     data_type={type}/year={yyyy}/month={mm}/day={dd}/{payload_id}.json.gz
 */
export interface RawProviderPayloadsTable {
  /** Internal UUID primary key (also used as the payload_id in the S3 key). */
  id: UuidPk;
  /** FK to `users.id`. */
  user_id: string;
  /** FK to `provider_connections.id`; nullable for batch/system-level imports. */
  provider_connection_id: NullableCol<string>;
  /** Canonical provider code per ADR-001. */
  provider_code: string;
  /** Provider-native data type identifier (e.g. 'sleep', 'daily-resting-heart-rate'). */
  provider_data_type: string;
  /** FK to the `provider_sync_jobs.id` that produced this payload. */
  sync_job_id: NullableCol<string>;
  /** S3 bucket name (without protocol prefix). */
  s3_bucket: string;
  /**
   * S3 object key path following the Data Model §8.7 convention.
   * Example: prod/user_id=abc/provider=google_health/data_type=sleep/year=2026/...
   */
  s3_key: string;
  /** SHA-256 hex digest of the raw payload (pre-compression). */
  content_sha256: string;
  /** Whether the S3 object is gzip-compressed (default true). */
  compressed: Generated<boolean>;
  /**
   * AWS KMS key ARN reference used for envelope encryption, if any.
   * NEVER the raw encryption key itself.
   */
  encryption_key_ref: NullableCol<string>;
  /** Start of the data time window covered by this payload (UTC). */
  payload_start_time_utc: NullableCol<Date>;
  /** End of the data time window covered by this payload (UTC). */
  payload_end_time_utc: NullableCol<Date>;
  /** Number of individual data records in this payload. */
  record_count: NullableCol<number>;
  /** Schema version of the payload format (for future deserialization). */
  schema_version: NullableCol<string>;
  /** UTC timestamp after which this payload may be deleted per retention policy. */
  retained_until: NullableCol<Date>;
  /** Free-form extension metadata. */
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
}

/** Full row shape returned by SELECT queries on `raw_provider_payloads`. */
export type RawProviderPayload = Selectable<RawProviderPayloadsTable>;
/** Shape accepted by INSERT queries on `raw_provider_payloads`. */
export type NewRawProviderPayload = Insertable<RawProviderPayloadsTable>;

// ---------------------------------------------------------------------------
// metric_definitions (000004_metrics.sql — §9.1)
// ---------------------------------------------------------------------------

/**
 * The canonical metric registry. One row per canonical metric code.
 *
 * Seeded from `@primis/health-metrics` METRIC_DEFINITIONS via `pnpm db:seed`.
 * Do NOT hand-write rows here — always derive from the TypeScript registry so
 * the two sources stay in sync (Data Model §9.2).
 *
 * `metric_code` is the primary key and is referenced by all observation,
 * summary, baseline, and score tables as a text FK.
 */
export interface MetricDefinitionsTable {
  /**
   * Unique string identifier. Sourced from Data Model §9.2.
   * Examples: 'steps', 'heart_rate', 'sleep_duration', 'recovery_score'.
   */
  metric_code: string;
  /** Human-readable label for UI and logging. */
  display_name: string;
  /**
   * Top-level health domain.
   * Allowed: 'activity' | 'sleep' | 'recovery' | 'vitals' | 'nutrition' |
   *   'body_composition' | 'manual' | 'derived' | 'score'
   */
  category: string;
  /**
   * Storage format for observed values.
   * Allowed: 'numeric' | 'boolean' | 'enum' | 'json'
   */
  value_type: string;
  /** Canonical unit string; null for dimensionless or json-typed metrics. */
  canonical_unit: NullableCol<string>;
  /**
   * Temporal granularity.
   * Allowed: 'point' | 'interval' | 'daily' | 'session' | 'event'
   */
  sampling_type: string;
  /**
   * Default rollup strategy for daily aggregation.
   * Allowed: 'sum' | 'avg' | 'min' | 'max' | 'latest' | 'duration_weighted_avg' | 'none'
   */
  default_aggregation: NullableCol<string>;
  /**
   * Scoring directionality.
   * true = higher is better; false = lower is better; null = context-dependent.
   */
  higher_is_better: NullableCol<boolean>;
  /** Population-level reference ranges (Phase F+). Default empty object. */
  normal_range: Generated<Record<string, unknown>>;
  /** Provider preference ordering for deduplication (Phase E+). Default empty object. */
  source_priority: Generated<Record<string, unknown>>;
  /** Human-readable note for engineers and AI agents. */
  description: NullableCol<string>;
  /** Whether this metric is currently in active use. */
  is_active: Generated<boolean>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

/** Full row shape returned by SELECT queries on `metric_definitions`. */
export type MetricDefinition = Selectable<MetricDefinitionsTable>;
/** Shape accepted by INSERT queries on `metric_definitions`. */
export type NewMetricDefinition = Insertable<MetricDefinitionsTable>;
/** Shape accepted by UPDATE queries on `metric_definitions`. */
export type MetricDefinitionUpdate = Updateable<MetricDefinitionsTable>;

// ---------------------------------------------------------------------------
// metric_observations (000004_metrics.sql — §10.2)
// ---------------------------------------------------------------------------

/**
 * Canonical scalar/boolean/enum/json observations from providers, manual
 * input, or Primis-derived calculations.
 *
 * Deduplication: unique(user_id, metric_code, source_provider, source_record_id).
 * Upsert via ON CONFLICT DO UPDATE in `metricRepository.upsertObservation()`.
 *
 * NOTE: NULL source_record_id values are not covered by the unique constraint
 * (NULL ≠ NULL in Postgres unique semantics). The repository must guard against
 * duplicate inserts for observation rows with no provider record ID.
 */
export interface MetricObservationsTable {
  /** UUID primary key; generated by gen_random_uuid(). */
  id: UuidPk;
  /** FK to `users.id`. */
  user_id: string;
  /** FK to `metric_definitions.metric_code`. */
  metric_code: string;
  /** FK to `provider_connections.id`; null for manual/derived observations. */
  provider_connection_id: NullableCol<string>;
  /**
   * Origin category.
   * Allowed: 'provider' | 'manual' | 'derived' | 'imported' | 'ai_assisted'
   */
  source_type: string;
  /**
   * Provider or source identifier.
   * Examples: 'google_health', 'healthkit', 'manual', 'primis_internal'
   */
  source_provider: string;
  /** Provider-assigned record ID; null for manual/derived observations. */
  source_record_id: NullableCol<string>;

  /** Observation start time in UTC. */
  start_time_utc: Date;
  /** Observation end time in UTC; null for point observations. */
  end_time_utc: NullableCol<Date>;
  /**
   * Calendar date in the user's primary timezone (ISO YYYY-MM-DD).
   * Required for correct daily-boundary analytics (ARCH-TIME-004).
   */
  local_date: string;
  /** IANA timezone string (e.g. 'America/New_York'). */
  timezone: string;

  /** Numeric observation value (double precision). */
  numeric_value: NullableCol<number>;
  /** String/enum observation value. */
  text_value: NullableCol<string>;
  /** Boolean observation value. */
  boolean_value: NullableCol<boolean>;
  /** JSON observation value (jsonb). */
  json_value: NullableCol<Record<string, unknown>>;
  /** Canonical unit string for this observation. */
  unit: NullableCol<string>;

  /**
   * Level of aggregation applied to this value.
   * Allowed: 'raw' | 'minute' | 'hour' | 'day' | 'session' | 'rolling'
   */
  aggregation_level: Generated<string>;
  /**
   * Method used to aggregate sub-observations.
   * Allowed: 'sum' | 'avg' | 'min' | 'max' | 'latest' | 'duration_weighted_avg'
   */
  aggregation_method: NullableCol<string>;

  /**
   * Data quality classification.
   * Allowed: 'normal' | 'estimated' | 'partial' | 'sparse' | 'stale' |
   *   'duplicate_candidate' | 'corrected' | 'low_confidence'
   */
  data_quality: Generated<string>;
  /** Internal confidence score (0.0000 – 1.0000). */
  confidence_score: NullableCol<string>;
  /** Number of sub-samples contributing to this aggregated observation. */
  sample_count: NullableCol<number>;
  /** Percentage of the expected observation window covered (0.00 – 100.00). */
  coverage_pct: NullableCol<string>;

  /** Free-form extension metadata. */
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

/** Full row shape returned by SELECT queries on `metric_observations`. */
export type MetricObservation = Selectable<MetricObservationsTable>;
/** Shape accepted by INSERT queries on `metric_observations`. */
export type NewMetricObservation = Insertable<MetricObservationsTable>;
/** Shape accepted by UPDATE queries on `metric_observations`. */
export type MetricObservationUpdate = Updateable<MetricObservationsTable>;

// ---------------------------------------------------------------------------
// metric_timeseries_samples (000004_metrics.sql — §10.3)
// ---------------------------------------------------------------------------

/**
 * Optional high-volume table for point-in-time samples such as continuous
 * heart rate. Use this table when metric_observations becomes too heavy for
 * high-frequency data.
 *
 * Deduplication: unique(user_id, metric_code, source_provider, timestamp_utc, source_record_id).
 */
export interface MetricTimeseriesSamplesTable {
  /** UUID primary key; generated by gen_random_uuid(). */
  id: UuidPk;
  /** FK to `users.id`. */
  user_id: string;
  /** FK to `metric_definitions.metric_code`. */
  metric_code: string;
  /** FK to `provider_connections.id`; null for manual/derived samples. */
  provider_connection_id: NullableCol<string>;
  /** Provider or source identifier. */
  source_provider: string;
  /** Provider-assigned record ID; null if unavailable. */
  source_record_id: NullableCol<string>;
  /** Sample timestamp in UTC. */
  timestamp_utc: Date;
  /** Calendar date in the user's primary timezone. */
  local_date: string;
  /** IANA timezone string. */
  timezone: string;
  /** Sample value (double precision). */
  numeric_value: number;
  /** Canonical unit string. */
  unit: string;
  /**
   * Data quality classification.
   * Allowed: 'normal' | 'estimated' | 'partial' | 'sparse' | 'stale' |
   *   'duplicate_candidate' | 'corrected' | 'low_confidence'
   */
  data_quality: Generated<string>;
  /** Free-form extension metadata. */
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
}

/** Full row shape returned by SELECT queries on `metric_timeseries_samples`. */
export type MetricTimeseriesSample = Selectable<MetricTimeseriesSamplesTable>;
/** Shape accepted by INSERT queries on `metric_timeseries_samples`. */
export type NewMetricTimeseriesSample = Insertable<MetricTimeseriesSamplesTable>;

// ---------------------------------------------------------------------------
// daily_metric_summaries (000004_metrics.sql — §10.4)
// ---------------------------------------------------------------------------

/**
 * Precomputed daily summaries for fast app screens and AI context retrieval.
 *
 * Rows are populated by the scoring/summary engine in Phase F+.
 * All numeric columns are nullable because summaries may be partial.
 *
 * One row per (user_id, local_date, metric_code, source_provider).
 * Multiple source rows may exist for the same (user + date + metric) when
 * multiple providers supply the same metric type.
 */
export interface DailyMetricSummariesTable {
  /** UUID primary key; generated by gen_random_uuid(). */
  id: UuidPk;
  /** FK to `users.id`. */
  user_id: string;
  /** Calendar date in the user's primary timezone. */
  local_date: string;
  /** IANA timezone string. */
  timezone: string;
  /** FK to `metric_definitions.metric_code`. */
  metric_code: string;

  /** Representative value for this metric on this date (provider/method-specific). */
  value: NullableCol<number>;
  /** Canonical unit string. */
  unit: NullableCol<string>;
  min_value: NullableCol<number>;
  max_value: NullableCol<number>;
  avg_value: NullableCol<number>;
  sum_value: NullableCol<number>;
  latest_value: NullableCol<number>;
  /** Number of raw samples contributing to this summary. */
  sample_count: Generated<number>;
  /** Percentage of the day covered by observations (0.00 – 100.00). */
  coverage_pct: NullableCol<string>;

  /** Originating provider code. */
  source_provider: NullableCol<string>;
  /** Priority rank when multiple providers supply the same metric (1 = highest). */
  source_priority_rank: NullableCol<number>;
  /**
   * Data quality classification.
   * Allowed: 'normal' | 'estimated' | 'partial' | 'sparse' | 'stale' |
   *   'duplicate_candidate' | 'corrected' | 'low_confidence'
   */
  data_quality: Generated<string>;
  /** Confidence score (0.0000 – 1.0000). */
  confidence_score: NullableCol<string>;
  /** Free-form component-level metadata (e.g. which observations contributed). */
  component_metadata: Generated<Record<string, unknown>>;

  /** UTC timestamp when this summary was last computed. */
  generated_at: Generated<Date>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

/** Full row shape returned by SELECT queries on `daily_metric_summaries`. */
export type DailyMetricSummary = Selectable<DailyMetricSummariesTable>;
/** Shape accepted by INSERT queries on `daily_metric_summaries`. */
export type NewDailyMetricSummary = Insertable<DailyMetricSummariesTable>;
/** Shape accepted by UPDATE queries on `daily_metric_summaries`. */
export type DailyMetricSummaryUpdate = Updateable<DailyMetricSummariesTable>;

// ---------------------------------------------------------------------------
// rolling_metric_baselines (000004_metrics.sql — §10.5)
// ---------------------------------------------------------------------------

/**
 * Personal rolling baselines for trend analysis and score computation.
 *
 * Rows are populated by the baseline engine in Phase F+.
 * One row per (user_id, metric_code, as_of_local_date, window_days, baseline_method).
 *
 * window_days: 7, 14, 28, 30, 60, 90, 180, 365
 * baseline_method: mean, median, ewma, trimmed_mean
 */
export interface RollingMetricBaselinesTable {
  /** UUID primary key; generated by gen_random_uuid(). */
  id: UuidPk;
  /** FK to `users.id`. */
  user_id: string;
  /** FK to `metric_definitions.metric_code`. */
  metric_code: string;
  /** Date as of which this baseline was calculated, in the user's local timezone. */
  as_of_local_date: string;
  /** IANA timezone string. */
  timezone: string;
  /** Rolling window in calendar days (7, 14, 28, 30, 60, 90, 180, 365). */
  window_days: number;
  /** Aggregation method: 'mean' | 'median' | 'ewma' | 'trimmed_mean'. */
  baseline_method: string;
  /** Computed baseline value. */
  baseline_value: NullableCol<number>;
  /** Standard deviation of the window sample. */
  stddev_value: NullableCol<number>;
  min_value: NullableCol<number>;
  max_value: NullableCol<number>;
  /** Number of calendar days with valid data in this window. */
  sample_days: Generated<number>;
  /** Percentage of expected days with data (0.00 – 100.00). */
  coverage_pct: NullableCol<string>;
  /** Confidence score (0.0000 – 1.0000). */
  confidence_score: NullableCol<string>;
  /** UTC timestamp when this baseline was generated. */
  generated_at: Generated<Date>;
  /** Free-form extension metadata. */
  metadata: Generated<Record<string, unknown>>;
}

/** Full row shape returned by SELECT queries on `rolling_metric_baselines`. */
export type RollingMetricBaseline = Selectable<RollingMetricBaselinesTable>;
/** Shape accepted by INSERT queries on `rolling_metric_baselines`. */
export type NewRollingMetricBaseline = Insertable<RollingMetricBaselinesTable>;
/** Shape accepted by UPDATE queries on `rolling_metric_baselines`. */
export type RollingMetricBaselineUpdate = Updateable<RollingMetricBaselinesTable>;

// ---------------------------------------------------------------------------
// sleep_sessions (000005_domain_tables.sql — §11.1)
// ---------------------------------------------------------------------------

/**
 * One provider sleep session.
 *
 * Deduplication: unique(user_id, source_provider, source_record_id).
 *
 * `local_sleep_date` follows the wake-date convention per ARCH-TIME-004:
 * sessions crossing midnight use the date the user woke up, not the date
 * sleep began.
 *
 * `provider_sleep_score` and `primis_sleep_score` are nullable because not
 * all providers expose score data and the Primis score is derived in Phase F.
 */
export interface SleepSessionsTable {
  id: UuidPk;
  user_id: string;
  provider_connection_id: NullableCol<string>;
  source_provider: string;
  source_record_id: NullableCol<string>;

  session_start_utc: Date;
  session_end_utc: Date;
  /** Date of wake-up (wake-date convention, ARCH-TIME-004). */
  local_sleep_date: string;
  timezone: string;

  time_in_bed_seconds: NullableCol<number>;
  total_sleep_seconds: NullableCol<number>;
  awake_seconds: NullableCol<number>;
  light_sleep_seconds: NullableCol<number>;
  deep_sleep_seconds: NullableCol<number>;
  rem_sleep_seconds: NullableCol<number>;
  unknown_sleep_seconds: NullableCol<number>;
  sleep_latency_seconds: NullableCol<number>;
  wake_after_sleep_onset_seconds: NullableCol<number>;
  sleep_efficiency_pct: NullableCol<string>;

  /** Provider-supplied sleep quality score; null if not exposed by the provider. */
  provider_sleep_score: NullableCol<string>;
  /** Primis-computed sleep score; derived in Phase F. Also stored in score_snapshots. */
  primis_sleep_score: NullableCol<string>;

  is_main_sleep: Generated<boolean>;
  /** nap_type: nap | main | unknown */
  nap_type: NullableCol<string>;
  data_quality: Generated<string>;
  confidence_score: NullableCol<string>;
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

export type SleepSession = Selectable<SleepSessionsTable>;
export type NewSleepSession = Insertable<SleepSessionsTable>;
export type SleepSessionUpdate = Updateable<SleepSessionsTable>;

// ---------------------------------------------------------------------------
// sleep_stage_intervals (000005_domain_tables.sql — §11.2)
// ---------------------------------------------------------------------------

/**
 * Granular sleep stage segments within a session.
 * Cascade-deleted when the parent `sleep_sessions` row is deleted.
 *
 * Allowed stage values: 'awake' | 'light' | 'deep' | 'rem' | 'asleep_unknown'
 */
export interface SleepStageIntervalsTable {
  id: UuidPk;
  sleep_session_id: string;
  user_id: string;
  /** stage: awake | light | deep | rem | asleep_unknown */
  stage: string;
  start_time_utc: Date;
  end_time_utc: Date;
  duration_seconds: number;
  source_provider: string;
  source_record_id: NullableCol<string>;
  confidence_score: NullableCol<string>;
  metadata: Generated<Record<string, unknown>>;
}

export type SleepStageInterval = Selectable<SleepStageIntervalsTable>;
export type NewSleepStageInterval = Insertable<SleepStageIntervalsTable>;

// ---------------------------------------------------------------------------
// sleep_daily_features (000005_domain_tables.sql — §11.3)
// ---------------------------------------------------------------------------

/**
 * Precomputed daily sleep features for scoring, AI context, and UI.
 *
 * Populated by the Phase F scoring engine. All computed columns are nullable
 * in Phase D because no values have been calculated yet.
 *
 * One row per (user_id, local_date) — enforced by unique constraint.
 */
export interface SleepDailyFeaturesTable {
  id: UuidPk;
  user_id: string;
  local_date: string;
  timezone: string;

  main_sleep_session_id: NullableCol<string>;
  bedtime_local: NullableCol<string>;
  wake_time_local: NullableCol<string>;
  midpoint_sleep_local: NullableCol<string>;

  /** Nullable until Phase F populates this row. */
  total_sleep_seconds: NullableCol<number>;
  time_in_bed_seconds: NullableCol<number>;
  sleep_efficiency_pct: NullableCol<string>;
  sleep_latency_seconds: NullableCol<number>;
  deep_sleep_pct: NullableCol<string>;
  rem_sleep_pct: NullableCol<string>;
  awake_pct: NullableCol<string>;

  sleep_debt_seconds: NullableCol<number>;
  sleep_consistency_score: NullableCol<string>;
  bedtime_regularity_score: NullableCol<string>;
  wake_time_regularity_score: NullableCol<string>;
  estimated_sleep_need_seconds: NullableCol<number>;
  chronotype_offset_minutes: NullableCol<number>;

  overnight_avg_hr: NullableCol<string>;
  overnight_min_hr: NullableCol<string>;
  overnight_hrv_rmssd: NullableCol<string>;
  overnight_resp_rate: NullableCol<string>;
  overnight_spo2_avg: NullableCol<string>;
  overnight_spo2_min: NullableCol<string>;

  data_quality: Generated<string>;
  confidence_score: NullableCol<string>;
  generated_at: Generated<Date>;
  metadata: Generated<Record<string, unknown>>;
}

export type SleepDailyFeatures = Selectable<SleepDailyFeaturesTable>;
export type NewSleepDailyFeatures = Insertable<SleepDailyFeaturesTable>;
export type SleepDailyFeaturesUpdate = Updateable<SleepDailyFeaturesTable>;

// ---------------------------------------------------------------------------
// bedtime_planner_requests (000005_domain_tables.sql — §11.4a)
// ---------------------------------------------------------------------------

/**
 * Records a user's bedtime planner request.
 *
 * Endpoints for this table are deferred to Phase G. The table is created now
 * so future phases have a stable FK target.
 *
 * Allowed source values: 'user' | 'home_widget' | 'ai_chat'
 */
export interface BedtimePlannerRequestsTable {
  id: UuidPk;
  user_id: string;
  target_wake_time_local: Date;
  timezone: string;
  desired_sleep_seconds: NullableCol<number>;
  flexible_wake_window_minutes: Generated<number>;
  next_day_context: Generated<Record<string, unknown>>;
  requested_at: Generated<Date>;
  /** source: user | home_widget | ai_chat */
  source: Generated<string>;
  metadata: Generated<Record<string, unknown>>;
}

export type BedtimePlannerRequest = Selectable<BedtimePlannerRequestsTable>;
export type NewBedtimePlannerRequest = Insertable<BedtimePlannerRequestsTable>;

// ---------------------------------------------------------------------------
// bedtime_recommendations (000005_domain_tables.sql — §11.4b)
// ---------------------------------------------------------------------------

/**
 * Ranked bedtime window recommendations for a planner request.
 * Cascade-deleted when the parent `bedtime_planner_requests` row is deleted.
 *
 * label values: 'best' | 'good' | 'last_acceptable' | 'recovery_priority' |
 *   'circadian_friendly'
 *
 * NOTE: `expected_cycles` is stored as a heuristic — do not overstate
 * physiological precision in UI or AI language per §11.4 guidance.
 */
export interface BedtimeRecommendationsTable {
  id: UuidPk;
  request_id: string;
  user_id: string;
  rank: number;
  /** label: best | good | last_acceptable | recovery_priority | circadian_friendly */
  label: string;

  recommended_bedtime_start_local: Date;
  recommended_bedtime_end_local: Date;
  estimated_fall_asleep_time_local: NullableCol<Date>;
  target_wake_time_local: Date;

  expected_sleep_opportunity_seconds: NullableCol<number>;
  expected_actual_sleep_seconds: NullableCol<number>;
  expected_cycles: NullableCol<string>;
  cycle_alignment_score: NullableCol<string>;
  circadian_alignment_score: NullableCol<string>;
  recovery_support_score: NullableCol<string>;
  overall_recommendation_score: NullableCol<string>;

  rationale_structured: Generated<Record<string, unknown>>;
  ai_explanation: NullableCol<string>;
  generated_at: Generated<Date>;
  metadata: Generated<Record<string, unknown>>;
}

export type BedtimeRecommendation = Selectable<BedtimeRecommendationsTable>;
export type NewBedtimeRecommendation = Insertable<BedtimeRecommendationsTable>;

// ---------------------------------------------------------------------------
// workout_sessions (000005_domain_tables.sql — §12.1)
// ---------------------------------------------------------------------------

/**
 * One provider workout event.
 *
 * Deduplication: unique(user_id, source_provider, source_record_id).
 *
 * `primis_strain_score` is derived by the Phase F scoring engine; also stored
 * in `score_snapshots`.
 */
export interface WorkoutSessionsTable {
  id: UuidPk;
  user_id: string;
  provider_connection_id: NullableCol<string>;
  source_provider: string;
  source_record_id: NullableCol<string>;

  workout_type: string;
  display_name: NullableCol<string>;
  start_time_utc: Date;
  end_time_utc: Date;
  local_date: string;
  timezone: string;

  duration_seconds: number;
  active_duration_seconds: NullableCol<number>;
  distance_m: NullableCol<number>;
  active_energy_kcal: NullableCol<number>;
  total_energy_kcal: NullableCol<number>;
  avg_hr_bpm: NullableCol<string>;
  max_hr_bpm: NullableCol<string>;
  min_hr_bpm: NullableCol<string>;
  elevation_gain_m: NullableCol<number>;
  steps_count: NullableCol<number>;

  provider_strain_score: NullableCol<string>;
  primis_strain_score: NullableCol<string>;
  training_load: NullableCol<string>;
  /** perceived_exertion: optional 1-10 manual override */
  perceived_exertion: NullableCol<number>;

  data_quality: Generated<string>;
  confidence_score: NullableCol<string>;
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

export type WorkoutSession = Selectable<WorkoutSessionsTable>;
export type NewWorkoutSession = Insertable<WorkoutSessionsTable>;
export type WorkoutSessionUpdate = Updateable<WorkoutSessionsTable>;

// ---------------------------------------------------------------------------
// workout_hr_zone_summaries (000005_domain_tables.sql — §12.2)
// ---------------------------------------------------------------------------

/**
 * Heart-rate zone summary for a workout session.
 * Cascade-deleted when the parent `workout_sessions` row is deleted.
 *
 * zone_code values: 'z1' | 'z2' | 'z3' | 'z4' | 'z5' | 'custom'
 * Unique on (workout_session_id, zone_code).
 */
export interface WorkoutHrZoneSummariesTable {
  id: UuidPk;
  workout_session_id: string;
  user_id: string;
  /** zone_code: z1 | z2 | z3 | z4 | z5 | custom */
  zone_code: string;
  zone_label: NullableCol<string>;
  lower_bpm: NullableCol<number>;
  upper_bpm: NullableCol<number>;
  duration_seconds: Generated<number>;
  calories_kcal: NullableCol<number>;
  metadata: Generated<Record<string, unknown>>;
}

export type WorkoutHrZoneSummary = Selectable<WorkoutHrZoneSummariesTable>;
export type NewWorkoutHrZoneSummary = Insertable<WorkoutHrZoneSummariesTable>;

// ---------------------------------------------------------------------------
// training_load_daily (000005_domain_tables.sql — §12.3)
// ---------------------------------------------------------------------------

/**
 * Daily training load aggregation. Populated by the Phase F scoring engine.
 *
 * All load metrics are nullable in Phase D. `workout_count` is non-null
 * (default 0) as it can be incremented when sessions are ingested.
 *
 * One row per (user_id, local_date).
 *
 * load_status values: 'well_below' | 'below' | 'steady' | 'above' | 'well_above'
 */
export interface TrainingLoadDailyTable {
  id: UuidPk;
  user_id: string;
  local_date: string;
  timezone: string;

  daily_training_load: NullableCol<string>;
  daily_strain_score: NullableCol<string>;
  workout_count: Generated<number>;
  active_energy_kcal: NullableCol<number>;
  active_minutes_seconds: NullableCol<number>;
  zone_minutes_seconds: NullableCol<number>;

  acute_load_7d: NullableCol<string>;
  chronic_load_28d: NullableCol<string>;
  acute_chronic_ratio: NullableCol<string>;
  /** load_status: well_below | below | steady | above | well_above */
  load_status: NullableCol<string>;

  generated_at: Generated<Date>;
  data_quality: Generated<string>;
  metadata: Generated<Record<string, unknown>>;
}

export type TrainingLoadDaily = Selectable<TrainingLoadDailyTable>;
export type NewTrainingLoadDaily = Insertable<TrainingLoadDailyTable>;
export type TrainingLoadDailyUpdate = Updateable<TrainingLoadDailyTable>;

// ---------------------------------------------------------------------------
// body_composition_measurements (000005_domain_tables.sql — §13.1)
// ---------------------------------------------------------------------------

/**
 * One scale/device body composition measurement.
 *
 * Deduplication: unique(user_id, source_provider, source_record_id).
 *
 * source_provider values: 'healthkit' | 'google_health' |
 *   'hume_via_healthkit' | 'manual'
 */
export interface BodyCompositionMeasurementsTable {
  id: UuidPk;
  user_id: string;
  provider_connection_id: NullableCol<string>;
  source_provider: string;
  source_record_id: NullableCol<string>;

  measured_at_utc: Date;
  local_date: string;
  timezone: string;

  weight_kg: NullableCol<string>;
  body_fat_pct: NullableCol<string>;
  lean_mass_kg: NullableCol<string>;
  fat_mass_kg: NullableCol<string>;
  bone_mass_kg: NullableCol<string>;
  body_water_pct: NullableCol<string>;
  visceral_fat_index: NullableCol<string>;
  bmr_kcal: NullableCol<string>;
  bmi: NullableCol<string>;

  segmental_data: Generated<Record<string, unknown>>;
  data_quality: Generated<string>;
  confidence_score: NullableCol<string>;
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

export type BodyCompositionMeasurement = Selectable<BodyCompositionMeasurementsTable>;
export type NewBodyCompositionMeasurement = Insertable<BodyCompositionMeasurementsTable>;
export type BodyCompositionMeasurementUpdate = Updateable<BodyCompositionMeasurementsTable>;

// ---------------------------------------------------------------------------
// vital_daily_features (000005_domain_tables.sql — §13.2)
// ---------------------------------------------------------------------------

/**
 * Daily vital-sign features. Populated by the Phase F scoring engine.
 *
 * All computed columns are nullable in Phase D. One row per (user_id, local_date).
 */
export interface VitalDailyFeaturesTable {
  id: UuidPk;
  user_id: string;
  local_date: string;
  timezone: string;

  /** Nullable until Phase F populates this row. */
  resting_heart_rate_bpm: NullableCol<string>;
  hrv_rmssd_ms: NullableCol<string>;
  avg_heart_rate_bpm: NullableCol<string>;
  min_heart_rate_bpm: NullableCol<string>;
  max_heart_rate_bpm: NullableCol<string>;
  avg_spo2_pct: NullableCol<string>;
  min_spo2_pct: NullableCol<string>;
  respiratory_rate_bpm: NullableCol<string>;
  skin_temp_delta_c: NullableCol<string>;
  vo2_max: NullableCol<string>;

  rhr_vs_30d_delta: NullableCol<string>;
  hrv_vs_30d_delta_pct: NullableCol<string>;
  resp_rate_vs_30d_delta: NullableCol<string>;
  spo2_vs_30d_delta: NullableCol<string>;

  data_quality: Generated<string>;
  confidence_score: NullableCol<string>;
  generated_at: Generated<Date>;
  metadata: Generated<Record<string, unknown>>;
}

export type VitalDailyFeatures = Selectable<VitalDailyFeaturesTable>;
export type NewVitalDailyFeatures = Insertable<VitalDailyFeaturesTable>;
export type VitalDailyFeaturesUpdate = Updateable<VitalDailyFeaturesTable>;

// ---------------------------------------------------------------------------
// manual_checkins (000005_domain_tables.sql — §14.1)
// ---------------------------------------------------------------------------

/**
 * Subjective daily check-in record.
 *
 * checkin_type values: 'daily' | 'post_workout' | 'sleep_reflection' |
 *   'nutrition' | 'digestion' | 'custom'
 *
 * All score columns are nullable (1–5 or 0–5 scale depending on metric).
 * `libido_score` is only collected when the user explicitly opts in.
 */
export interface ManualCheckinsTable {
  id: UuidPk;
  user_id: string;
  /** checkin_type: daily | post_workout | sleep_reflection | nutrition | digestion | custom */
  checkin_type: string;
  occurred_at_utc: Date;
  local_date: string;
  timezone: string;

  energy_score: NullableCol<number>;
  mood_score: NullableCol<number>;
  stress_score: NullableCol<number>;
  soreness_score: NullableCol<number>;
  productivity_score: NullableCol<number>;
  motivation_score: NullableCol<number>;
  /** libido_score: collected only when user enables this optional metric. */
  libido_score: NullableCol<number>;

  notes: NullableCol<string>;
  completion_seconds: NullableCol<number>;
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

export type ManualCheckin = Selectable<ManualCheckinsTable>;
export type NewManualCheckin = Insertable<ManualCheckinsTable>;
export type ManualCheckinUpdate = Updateable<ManualCheckinsTable>;

// ---------------------------------------------------------------------------
// custom_tags (000005_domain_tables.sql — §14.2)
// ---------------------------------------------------------------------------

/**
 * User-defined or system-suggested event tags.
 *
 * Unique on (user_id, tag_code).
 *
 * category values: 'food' | 'training' | 'sleep' | 'stress' | 'supplement' |
 *   'lifestyle' | 'custom'
 */
export interface CustomTagsTable {
  id: UuidPk;
  user_id: string;
  tag_code: string;
  display_name: string;
  /** category: food | training | sleep | stress | supplement | lifestyle | custom */
  category: NullableCol<string>;
  is_system_suggested: Generated<boolean>;
  is_active: Generated<boolean>;
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

export type CustomTag = Selectable<CustomTagsTable>;
export type NewCustomTag = Insertable<CustomTagsTable>;
export type CustomTagUpdate = Updateable<CustomTagsTable>;

// ---------------------------------------------------------------------------
// tag_events (000005_domain_tables.sql — §14.3)
// ---------------------------------------------------------------------------

/**
 * Records of a custom tag being applied at a specific time.
 *
 * linked_entity_type values: 'nutrition_entry' | 'workout_session' |
 *   'sleep_session' | 'manual_checkin'
 */
export interface TagEventsTable {
  id: UuidPk;
  user_id: string;
  custom_tag_id: NullableCol<string>;
  tag_code: string;
  occurred_at_utc: Date;
  local_date: string;
  timezone: string;
  intensity: NullableCol<number>;
  quantity: NullableCol<string>;
  unit: NullableCol<string>;
  notes: NullableCol<string>;
  /** linked_entity_type: nutrition_entry | workout_session | sleep_session | manual_checkin */
  linked_entity_type: NullableCol<string>;
  linked_entity_id: NullableCol<string>;
  created_at: CreatedAt;
  metadata: Generated<Record<string, unknown>>;
}

export type TagEvent = Selectable<TagEventsTable>;
export type NewTagEvent = Insertable<TagEventsTable>;

// ---------------------------------------------------------------------------
// hydration_entries (000005_domain_tables.sql — §14.4)
// ---------------------------------------------------------------------------

/**
 * Fluid intake log entry.
 *
 * source_type values: 'manual' | 'provider'
 */
export interface HydrationEntriesTable {
  id: UuidPk;
  user_id: string;
  /** source_type: manual | provider */
  source_type: Generated<string>;
  occurred_at_utc: Date;
  local_date: string;
  timezone: string;
  amount_ml: string;
  beverage_type: NullableCol<string>;
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
}

export type HydrationEntry = Selectable<HydrationEntriesTable>;
export type NewHydrationEntry = Insertable<HydrationEntriesTable>;

// ---------------------------------------------------------------------------
// caffeine_entries (000005_domain_tables.sql — §14.5)
// ---------------------------------------------------------------------------

/**
 * Caffeine intake log entry.
 *
 * beverage_type values: 'coffee' | 'espresso' | 'energy_drink' | 'tea' |
 *   'preworkout' | 'other'
 */
export interface CaffeineEntriesTable {
  id: UuidPk;
  user_id: string;
  occurred_at_utc: Date;
  local_date: string;
  timezone: string;
  caffeine_mg: NullableCol<string>;
  /** beverage_type: coffee | espresso | energy_drink | tea | preworkout | other */
  beverage_type: NullableCol<string>;
  serving_description: NullableCol<string>;
  estimated: Generated<boolean>;
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
}

export type CaffeineEntry = Selectable<CaffeineEntriesTable>;
export type NewCaffeineEntry = Insertable<CaffeineEntriesTable>;

// ---------------------------------------------------------------------------
// alcohol_entries (000005_domain_tables.sql — §14.6)
// ---------------------------------------------------------------------------

/**
 * Alcohol intake log entry.
 *
 * drink_range values: 'none' | 'one' | 'two' | 'three_four' | 'five_plus'
 * alcohol_type values: 'beer' | 'wine' | 'liquor' | 'cocktail' | 'mixed' | 'other'
 */
export interface AlcoholEntriesTable {
  id: UuidPk;
  user_id: string;
  occurred_at_utc: Date;
  local_date: string;
  timezone: string;
  standard_drinks: string;
  /** drink_range: none | one | two | three_four | five_plus */
  drink_range: NullableCol<string>;
  /** alcohol_type: beer | wine | liquor | cocktail | mixed | other */
  alcohol_type: NullableCol<string>;
  last_drink_time_utc: NullableCol<Date>;
  notes: NullableCol<string>;
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
}

export type AlcoholEntry = Selectable<AlcoholEntriesTable>;
export type NewAlcoholEntry = Insertable<AlcoholEntriesTable>;

// ---------------------------------------------------------------------------
// bowel_entries (000005_domain_tables.sql — §14.7)
// ---------------------------------------------------------------------------

/**
 * Optional gut health tracking. S3-like sensitivity level.
 *
 * Use for trend/correlation only. Do not diagnose disease.
 *
 * bristol_type: 1–7 (Bristol Stool Scale)
 * color: brown | green | yellow | black | red | pale | other | unknown
 * smell: normal | strong | sulfur | unusual | unknown
 * urgency: none | mild | urgent
 * completeness: incomplete | normal | complete | unknown
 */
export interface BowelEntriesTable {
  id: UuidPk;
  user_id: string;
  occurred_at_utc: Date;
  local_date: string;
  timezone: string;

  /** bristol_type: 1–7; null if not provided. */
  bristol_type: NullableCol<number>;
  color: NullableCol<string>;
  smell: NullableCol<string>;
  urgency: NullableCol<string>;
  /** pain_level: 0–5 */
  pain_level: NullableCol<number>;
  /** bloating_level: 0–5 */
  bloating_level: NullableCol<number>;
  completeness: NullableCol<string>;
  notes: NullableCol<string>;

  data_quality: Generated<string>;
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

export type BowelEntry = Selectable<BowelEntriesTable>;
export type NewBowelEntry = Insertable<BowelEntriesTable>;
export type BowelEntryUpdate = Updateable<BowelEntriesTable>;

// ---------------------------------------------------------------------------
// food_catalog_sources (000005_domain_tables.sql — §15.1)
// ---------------------------------------------------------------------------

/**
 * Registry of food data catalog origins.
 *
 * `source_code` is the primary key and is referenced by `food_items`.
 * Seeded with 'fdc' (USDA FoodData Central) in the migration.
 *
 * Example source_code values: 'fdc' | 'user_private' | 'user_approved_global' |
 *   'manual' | 'future_mfp_official'
 */
export interface FoodCatalogSourcesTable {
  source_code: string;
  display_name: string;
  license_name: NullableCol<string>;
  attribution_text: NullableCol<string>;
  source_version: NullableCol<string>;
  source_url: NullableCol<string>;
  imported_at: NullableCol<Date>;
  metadata: Generated<Record<string, unknown>>;
}

export type FoodCatalogSource = Selectable<FoodCatalogSourcesTable>;
export type NewFoodCatalogSource = Insertable<FoodCatalogSourcesTable>;

// ---------------------------------------------------------------------------
// food_items (000005_domain_tables.sql — §15.2)
// ---------------------------------------------------------------------------

/**
 * Global or user-created food records.
 *
 * `search_vector` tsvector column is present but the GIN index is deferred
 * to Phase K (FoodData Central bulk import) per the migration plan.
 *
 * visibility values: 'global' | 'private' | 'public_pending' |
 *   'public_approved' | 'hidden'
 * verified_status values: 'verified' | 'imported' | 'user_created' |
 *   'unverified' | 'deprecated'
 * data_type values: 'foundation' | 'sr_legacy' | 'survey' | 'branded' |
 *   'user_created'
 *
 * Unique on (source_code, external_food_id).
 */
export interface FoodItemsTable {
  id: UuidPk;
  source_code: string;
  external_food_id: NullableCol<string>;
  /** null for global catalog items; set for user-created foods. */
  owner_user_id: NullableCol<string>;
  /** visibility: global | private | public_pending | public_approved | hidden */
  visibility: Generated<string>;

  name: string;
  brand_name: NullableCol<string>;
  description: NullableCol<string>;
  food_category: NullableCol<string>;
  /** data_type: foundation | sr_legacy | survey | branded | user_created */
  data_type: NullableCol<string>;

  serving_size: NullableCol<string>;
  serving_unit: NullableCol<string>;
  household_serving: NullableCol<string>;

  calories_kcal: NullableCol<string>;
  protein_g: NullableCol<string>;
  carbs_g: NullableCol<string>;
  fat_g: NullableCol<string>;
  fiber_g: NullableCol<string>;
  sugar_g: NullableCol<string>;
  sodium_mg: NullableCol<string>;

  /** verified_status: verified | imported | user_created | unverified | deprecated */
  verified_status: Generated<string>;
  /** tsvector for full-text search; GIN index deferred until Phase K. */
  search_vector: NullableCol<string>;
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

export type FoodItem = Selectable<FoodItemsTable>;
export type NewFoodItem = Insertable<FoodItemsTable>;
export type FoodItemUpdate = Updateable<FoodItemsTable>;

// ---------------------------------------------------------------------------
// food_nutrient_values (000005_domain_tables.sql — §15.3)
// ---------------------------------------------------------------------------

/**
 * Detailed micro/macro nutrient values per food item.
 * Cascade-deleted when the parent `food_items` row is deleted.
 *
 * Unique on (food_item_id, nutrient_code).
 */
export interface FoodNutrientValuesTable {
  id: UuidPk;
  food_item_id: string;
  nutrient_code: string;
  nutrient_name: string;
  amount: NullableCol<string>;
  unit: string;
  derivation_code: NullableCol<string>;
  metadata: Generated<Record<string, unknown>>;
}

export type FoodNutrientValue = Selectable<FoodNutrientValuesTable>;
export type NewFoodNutrientValue = Insertable<FoodNutrientValuesTable>;

// ---------------------------------------------------------------------------
// nutrition_entries (000005_domain_tables.sql — §15.4)
// ---------------------------------------------------------------------------

/**
 * Meal / logging event.
 *
 * meal_type values: 'breakfast' | 'lunch' | 'dinner' | 'snack' |
 *   'preworkout' | 'postworkout' | 'unknown'
 * entry_method values: 'manual_macros' | 'food_search' | 'ai_text_estimate' |
 *   'photo_estimate' | 'barcode' | 'imported'
 * data_quality values: 'normal' | 'estimated' | 'low_confidence' | 'incomplete'
 */
export interface NutritionEntriesTable {
  id: UuidPk;
  user_id: string;
  occurred_at_utc: Date;
  local_date: string;
  timezone: string;
  /** meal_type: breakfast | lunch | dinner | snack | preworkout | postworkout | unknown */
  meal_type: NullableCol<string>;
  /** entry_method: manual_macros | food_search | ai_text_estimate | photo_estimate | barcode | imported */
  entry_method: string;
  description: NullableCol<string>;

  total_calories_kcal: NullableCol<string>;
  total_protein_g: NullableCol<string>;
  total_carbs_g: NullableCol<string>;
  total_fat_g: NullableCol<string>;
  total_fiber_g: NullableCol<string>;
  total_sugar_g: NullableCol<string>;
  total_sodium_mg: NullableCol<string>;

  confidence_score: NullableCol<string>;
  data_quality: Generated<string>;
  ai_estimated: Generated<boolean>;
  notes: NullableCol<string>;
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

export type NutritionEntry = Selectable<NutritionEntriesTable>;
export type NewNutritionEntry = Insertable<NutritionEntriesTable>;
export type NutritionEntryUpdate = Updateable<NutritionEntriesTable>;

// ---------------------------------------------------------------------------
// nutrition_entry_items (000005_domain_tables.sql — §15.5)
// ---------------------------------------------------------------------------

/**
 * Individual food items within a nutrition entry.
 * Cascade-deleted when the parent `nutrition_entries` row is deleted.
 */
export interface NutritionEntryItemsTable {
  id: UuidPk;
  nutrition_entry_id: string;
  user_id: string;
  /** null for free-form entries without a food catalog lookup. */
  food_item_id: NullableCol<string>;
  name_snapshot: string;
  brand_snapshot: NullableCol<string>;
  quantity: NullableCol<string>;
  unit: NullableCol<string>;
  serving_multiplier: NullableCol<string>;

  calories_kcal: NullableCol<string>;
  protein_g: NullableCol<string>;
  carbs_g: NullableCol<string>;
  fat_g: NullableCol<string>;
  fiber_g: NullableCol<string>;
  sugar_g: NullableCol<string>;
  sodium_mg: NullableCol<string>;

  confidence_score: NullableCol<string>;
  metadata: Generated<Record<string, unknown>>;
}

export type NutritionEntryItem = Selectable<NutritionEntryItemsTable>;
export type NewNutritionEntryItem = Insertable<NutritionEntryItemsTable>;

// ---------------------------------------------------------------------------
// daily_nutrition_summaries (000005_domain_tables.sql — §15.6)
// ---------------------------------------------------------------------------

/**
 * Precomputed daily nutrition totals. Populated by the Phase F scoring engine.
 *
 * All computed columns are nullable in Phase D. One row per (user_id, local_date).
 */
export interface DailyNutritionSummariesTable {
  id: UuidPk;
  user_id: string;
  local_date: string;
  timezone: string;

  /** Nullable until Phase F populates this row. */
  calories_in_kcal: NullableCol<string>;
  calories_out_kcal: NullableCol<string>;
  calorie_balance_kcal: NullableCol<string>;
  protein_g: NullableCol<string>;
  carbs_g: NullableCol<string>;
  fat_g: NullableCol<string>;
  fiber_g: NullableCol<string>;
  hydration_ml: NullableCol<string>;
  caffeine_mg: NullableCol<string>;
  latest_caffeine_time_utc: NullableCol<Date>;
  alcohol_standard_drinks: NullableCol<string>;

  protein_target_g: NullableCol<string>;
  calorie_target_kcal: NullableCol<string>;
  hydration_target_ml: NullableCol<string>;
  nutrition_score: NullableCol<string>;

  generated_at: Generated<Date>;
  data_quality: Generated<string>;
  metadata: Generated<Record<string, unknown>>;
}

export type DailyNutritionSummary = Selectable<DailyNutritionSummariesTable>;
export type NewDailyNutritionSummary = Insertable<DailyNutritionSummariesTable>;
export type DailyNutritionSummaryUpdate = Updateable<DailyNutritionSummariesTable>;

// ---------------------------------------------------------------------------
// Database interface
// ---------------------------------------------------------------------------

/**
 * The root Kysely `Database` interface mapping table names to their row types.
 *
 * Pass this as the generic parameter when constructing the Kysely instance:
 *
 * ```typescript
 * import { Kysely } from 'kysely';
 * import type { Database } from './types.js';
 *
 * const db = new Kysely<Database>({ dialect });
 * ```
 *
 * The `schema_migrations` table is included so the migration runner can perform
 * type-safe inserts and selects when tracking applied migration versions.
 */
export interface Database {
  schema_migrations: SchemaMigrationsTable;

  // CU-027: Identity, preferences, and consent
  users: UsersTable;
  auth_identities: AuthIdentitiesTable;
  user_goals: UserGoalsTable;
  coach_preferences: CoachPreferencesTable;
  nutrition_philosophy_preferences: NutritionPhilosophyPreferencesTable;
  consent_records: ConsentRecordsTable;
  data_retention_preferences: DataRetentionPreferencesTable;

  // CU-028: Provider connection and sync tables
  provider_connections: ProviderConnectionsTable;
  provider_data_availability: ProviderDataAvailabilityTable;
  provider_metric_mappings: ProviderMetricMappingsTable;
  provider_sync_jobs: ProviderSyncJobsTable;
  provider_sync_cursors: ProviderSyncCursorsTable;
  raw_provider_payloads: RawProviderPayloadsTable;

  // CU-029: Metric registry and observation tables
  metric_definitions: MetricDefinitionsTable;
  metric_observations: MetricObservationsTable;
  metric_timeseries_samples: MetricTimeseriesSamplesTable;
  daily_metric_summaries: DailyMetricSummariesTable;
  rolling_metric_baselines: RollingMetricBaselinesTable;

  // CU-030: Domain tables — sleep, activity, body composition, manual inputs, nutrition
  sleep_sessions: SleepSessionsTable;
  sleep_stage_intervals: SleepStageIntervalsTable;
  sleep_daily_features: SleepDailyFeaturesTable;
  bedtime_planner_requests: BedtimePlannerRequestsTable;
  bedtime_recommendations: BedtimeRecommendationsTable;
  workout_sessions: WorkoutSessionsTable;
  workout_hr_zone_summaries: WorkoutHrZoneSummariesTable;
  training_load_daily: TrainingLoadDailyTable;
  body_composition_measurements: BodyCompositionMeasurementsTable;
  vital_daily_features: VitalDailyFeaturesTable;
  manual_checkins: ManualCheckinsTable;
  custom_tags: CustomTagsTable;
  tag_events: TagEventsTable;
  hydration_entries: HydrationEntriesTable;
  caffeine_entries: CaffeineEntriesTable;
  alcohol_entries: AlcoholEntriesTable;
  bowel_entries: BowelEntriesTable;
  food_catalog_sources: FoodCatalogSourcesTable;
  food_items: FoodItemsTable;
  food_nutrient_values: FoodNutrientValuesTable;
  nutrition_entries: NutritionEntriesTable;
  nutrition_entry_items: NutritionEntryItemsTable;
  daily_nutrition_summaries: DailyNutritionSummariesTable;
}

// Re-export Generated and Kysely DML helpers for use in table definitions added by later CUs.
export type { Generated, Selectable, Insertable, Updateable };
