/**
 * Kysely `Database` interface — the central registry of all typed table definitions.
 *
 * Each schema CU adds table interfaces here:
 *   - CU-027: identity, preferences, consent tables
 *   - CU-028: provider connection and sync tables
 *   - CU-029: metric registry and observation tables
 *   - CU-030: domain tables (sleep, activity, body, manual, nutrition)
 *   - CU-031: score, insight, AI, and dashboard tables
 *
 * The `Database` interface is intentionally maintained by hand rather than generated
 * by a tool like `kysely-codegen`. The SQL migration files in `database/migrations/`
 * are the canonical schema source. Types here must accurately reflect those files.
 * See ADR-003 for the rationale.
 *
 * Internal-use table: `schema_migrations` is tracked here as a `SchemaMigrationsTable`
 * so the migration runner can query it in a type-safe manner.
 *
 * Column type conventions used throughout this file:
 *   - `Generated<T>`     — column has a DB default; T is required on SELECT,
 *                          optional on INSERT, and T on UPDATE. Imported from kysely.
 *   - `UuidPk`           — UUID primary key with gen_random_uuid() default;
 *                          optional on INSERT, never updated.
 *   - `CreatedAt`        — timestamptz with now() default; optional on INSERT,
 *                          immutable after creation (never update).
 *   - `UpdatedAt`        — timestamptz with now() default; optional on INSERT,
 *                          set explicitly by repository write methods (D-A-008).
 *   - `NullableCol<T>`   — nullable column; T | null on SELECT and UPDATE,
 *                          optional (T | null | undefined) on INSERT.
 *
 * Note on `exactOptionalPropertyTypes: true`:
 *   Kysely's `Insertable<T>` and `Updateable<T>` helpers generate correct optional
 *   property types. Repositories should use `Insertable<XTable>` and `Updateable<XTable>`
 *   rather than hand-writing `field?: T | undefined` in function signatures.
 */

import type { ColumnType, Generated, Selectable, Insertable, Updateable } from 'kysely';

// ---------------------------------------------------------------------------
// Shared column-type aliases
// ---------------------------------------------------------------------------

/** UUID primary key with `gen_random_uuid()` default. Never updated. */
type UuidPk = ColumnType<string, string | undefined, never>;

/** `created_at timestamptz not null default now()` — immutable after creation. */
type CreatedAt = ColumnType<Date, Date | undefined, never>;

/**
 * `updated_at timestamptz not null default now()` — set explicitly by
 * repository write methods on every mutation (D-A-008, no DB trigger).
 */
type UpdatedAt = Generated<Date>;

/**
 * Nullable column that may be omitted on INSERT (becomes NULL in the DB).
 * Maps to `T | null` on SELECT/UPDATE and `T | null | undefined` on INSERT
 * so Kysely's `Insertable<T>` renders the field as optional.
 */
type NullableCol<T> = ColumnType<T | null, T | null | undefined, T | null>;

// ---------------------------------------------------------------------------
// schema_migrations (migration tracking — 000001_init.sql)
// ---------------------------------------------------------------------------

/**
 * Row shape for the `schema_migrations` tracking table.
 * Managed exclusively by the migration runner — not exposed via repositories.
 */
export interface SchemaMigrationsTable {
  /** Filename stem of the applied migration, e.g. '000001_init'. */
  version: string;
  /** Timestamp when the migration was applied; DB-generated default. */
  applied_at: ColumnType<Date, never, never>;
}

/** Selectable row type for `schema_migrations`. */
export type SchemaMigration = Selectable<SchemaMigrationsTable>;

/** Insertable row type for `schema_migrations`. */
export type NewSchemaMigration = Insertable<SchemaMigrationsTable>;

// ---------------------------------------------------------------------------
// users (000002_identity_preferences.sql — §7.1)
// ---------------------------------------------------------------------------

/**
 * Core application identity.
 *
 * Key design points:
 *   - `id` is the internal UUID — the primary key for all health-data FK references
 *     (ARCH-AUTH-001). Never expose `id` directly to clients.
 *   - `cognito_sub` is stored as a separate unique text field. It is the lookup key
 *     used by the auth middleware to resolve internal user identity (ARCH-AUTH-002).
 *   - `sex_at_birth`, `date_of_birth`, and `height_cm` are optional user-controlled
 *     biometrics. Never infer or require these.
 */
export interface UsersTable {
  /** Internal UUID primary key; generated by `gen_random_uuid()`. */
  id: UuidPk;
  /** Cognito `sub` claim from the user's ID token. Unique across all users. */
  cognito_sub: string;
  /** Primary email address; null until verified or provided during sign-up. */
  email: NullableCol<string>;
  /** Whether the email address has been verified via Cognito. */
  email_verified: Generated<boolean>;
  /** Display name shown in the app. */
  display_name: NullableCol<string>;
  /**
   * Account lifecycle status.
   * Allowed values: 'active' | 'suspended' | 'deletion_requested' | 'deleted'
   */
  status: Generated<string>;
  /** IANA timezone string for the user's primary local zone, e.g. 'America/New_York'. */
  primary_timezone: Generated<string>;
  /**
   * Date of birth in ISO format (YYYY-MM-DD), returned as string by node-postgres.
   * Optional; do not require or infer.
   */
  date_of_birth: NullableCol<string>;
  /**
   * Biological sex at birth — user-controlled, optional.
   * Do not infer demographic data.
   */
  sex_at_birth: NullableCol<string>;
  /**
   * Height in centimetres (numeric(6,2)); returned as string by node-postgres.
   * Optional; used to improve VO2/body-composition interpretation.
   */
  height_cm: NullableCol<string>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  /** Set when user requests deletion; null for active accounts. */
  deleted_at: NullableCol<Date>;
}

/** Full row shape returned by SELECT queries on `users`. */
export type User = Selectable<UsersTable>;
/** Shape accepted by INSERT queries on `users`. */
export type NewUser = Insertable<UsersTable>;
/** Shape accepted by UPDATE queries on `users`. */
export type UserUpdate = Updateable<UsersTable>;

// ---------------------------------------------------------------------------
// auth_identities (000002_identity_preferences.sql — §7.2)
// ---------------------------------------------------------------------------

/**
 * Links sign-in methods to a Primis user account.
 *
 * IMPORTANT: `provider` values represent app authentication methods only.
 * Allowed: 'email_password' | 'google' | 'apple' | 'facebook'
 *
 * 'google' here means signing into Primis with a Google account (OAuth sign-in).
 * It is NOT the same as Google Health API authorization, which is tracked in
 * `provider_connections` (CU-028). See TAD §9.2.
 */
export interface AuthIdentitiesTable {
  /** Internal UUID primary key. */
  id: UuidPk;
  /** FK to `users.id`. */
  user_id: string;
  /**
   * App sign-in method.
   * Allowed values: 'email_password' | 'google' | 'apple' | 'facebook'
   */
  provider: string;
  /** Provider-assigned subject identifier (e.g. Google sub claim). */
  provider_subject: string;
  /** Email associated with this identity (may differ from users.email). */
  email: NullableCol<string>;
  linked_at: CreatedAt;
  /** Null until the user has authenticated via this identity at least once. */
  last_used_at: NullableCol<Date>;
}

/** Full row shape returned by SELECT queries on `auth_identities`. */
export type AuthIdentity = Selectable<AuthIdentitiesTable>;
/** Shape accepted by INSERT queries on `auth_identities`. */
export type NewAuthIdentity = Insertable<AuthIdentitiesTable>;
/** Shape accepted by UPDATE queries on `auth_identities`. */
export type AuthIdentityUpdate = Updateable<AuthIdentitiesTable>;

// ---------------------------------------------------------------------------
// user_goals (000002_identity_preferences.sql — §7.3)
// ---------------------------------------------------------------------------

/**
 * Ranked product goals selected during onboarding.
 *
 * `goal_code` values are application-level enums validated by Zod (D-A-009).
 * No DB CHECK constraint so the list can extend without a migration.
 * Current values: 'athletic_performance' | 'sleep' | 'body_composition' |
 *   'fat_loss' | 'muscle_gain' | 'longevity' | 'general_health'
 */
export interface UserGoalsTable {
  /** Internal UUID primary key. */
  id: UuidPk;
  /** FK to `users.id`. */
  user_id: string;
  /**
   * Goal identifier. Application-level enum; see GoalCode in api-contracts (CU-033).
   */
  goal_code: string;
  /** Ordering rank (1 = highest priority). */
  priority_rank: number;
  is_active: Generated<boolean>;
  /** Free-form extension data. */
  metadata: Generated<Record<string, unknown>>;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
}

/** Full row shape returned by SELECT queries on `user_goals`. */
export type UserGoal = Selectable<UserGoalsTable>;
/** Shape accepted by INSERT queries on `user_goals`. */
export type NewUserGoal = Insertable<UserGoalsTable>;
/** Shape accepted by UPDATE queries on `user_goals`. */
export type UserGoalUpdate = Updateable<UserGoalsTable>;

// ---------------------------------------------------------------------------
// coach_preferences (000002_identity_preferences.sql — §7.4)
// ---------------------------------------------------------------------------

/**
 * Coach tone and summary style preferences.
 * One row per user; `user_id` is both the primary key and FK to `users`.
 *
 * Allowed coach_style values:
 *   'analyst_coach' | 'strict' | 'encouraging' | 'performance_coach' |
 *   'calm' | 'concise' | 'explanatory' | 'unhinged_lite'
 */
export interface CoachPreferencesTable {
  /** PK and FK to `users.id` (1-to-1 relationship). */
  user_id: string;
  /**
   * Overall coaching persona.
   * Allowed values enforced by DB CHECK constraint.
   */
  coach_style: Generated<string>;
  /** Summary tone. */
  summary_style: Generated<string>;
  /**
   * Level of explanation detail.
   * Allowed: 'concise' | 'balanced' | 'detailed' | 'data_heavy'
   */
  explanation_depth: Generated<string>;
  /**
   * Push frequency/firmness.
   * Allowed: 'gentle' | 'moderate' | 'strict'
   */
  coaching_intensity: Generated<string>;
  /**
   * Humor tone.
   * Allowed: 'none' | 'low' | 'medium'
   */
  humor_level: Generated<string>;
  /** Enables the 'unhinged_lite' coach persona when true. */
  allow_unhinged_lite: Generated<boolean>;
  updated_at: UpdatedAt;
}

/** Full row shape returned by SELECT queries on `coach_preferences`. */
export type CoachPreferences = Selectable<CoachPreferencesTable>;
/** Shape accepted by INSERT queries on `coach_preferences`. */
export type NewCoachPreferences = Insertable<CoachPreferencesTable>;
/** Shape accepted by UPDATE queries on `coach_preferences`. */
export type CoachPreferencesUpdate = Updateable<CoachPreferencesTable>;

// ---------------------------------------------------------------------------
// nutrition_philosophy_preferences (000002_identity_preferences.sql — §7.5)
// ---------------------------------------------------------------------------

/**
 * User-selectable nutrition leanings.
 * One row per user; `user_id` is both the primary key and FK to `users`.
 *
 * Defaults reflect a whole-foods, high-protein, anti-inflammatory baseline.
 * All flags are freely overridable by the user.
 */
export interface NutritionPhilosophyPreferencesTable {
  /** PK and FK to `users.id` (1-to-1 relationship). */
  user_id: string;
  whole_foods_emphasis: Generated<boolean>;
  high_protein_emphasis: Generated<boolean>;
  animal_product_positive: Generated<boolean>;
  avoid_seed_oils: Generated<boolean>;
  avoid_artificial_dyes: Generated<boolean>;
  avoid_ultra_processed_foods: Generated<boolean>;
  anti_inflammatory_emphasis: Generated<boolean>;
  /** Free-text notes for custom nutrition constraints or preferences. */
  custom_notes: NullableCol<string>;
  updated_at: UpdatedAt;
}

/** Full row shape returned by SELECT queries on `nutrition_philosophy_preferences`. */
export type NutritionPhilosophyPreferences = Selectable<NutritionPhilosophyPreferencesTable>;
/** Shape accepted by INSERT queries on `nutrition_philosophy_preferences`. */
export type NewNutritionPhilosophyPreferences = Insertable<NutritionPhilosophyPreferencesTable>;
/** Shape accepted by UPDATE queries on `nutrition_philosophy_preferences`. */
export type NutritionPhilosophyPreferencesUpdate = Updateable<NutritionPhilosophyPreferencesTable>;

// ---------------------------------------------------------------------------
// consent_records (000002_identity_preferences.sql — §7.6)
// ---------------------------------------------------------------------------

/**
 * Append-only log of meaningful consent events.
 *
 * Allowed consent_type values:
 *   'terms' | 'privacy_policy' | 'ai_processing' | 'google_health' |
 *   'healthkit' | 'health_connect' | 'data_retention' | 'marketing'
 *
 * Note: `ip_hash` and `user_agent_hash` are hashed client metadata for audit
 * purposes. Raw IP addresses and user-agent strings must never be stored.
 */
export interface ConsentRecordsTable {
  /** Internal UUID primary key. */
  id: UuidPk;
  /** FK to `users.id`. */
  user_id: string;
  /**
   * Type of consent event. Enforced by DB CHECK constraint.
   */
  consent_type: string;
  /** Policy or document version the user consented to, e.g. '1.0'. */
  version: string;
  /** True if consent was granted; false if declined or revoked. */
  granted: boolean;
  granted_at: CreatedAt;
  /** Set when consent is revoked after having been granted. */
  revoked_at: NullableCol<Date>;
  /** SHA-256 hash of the client IP address (for audit; never the raw IP). */
  ip_hash: NullableCol<string>;
  /** SHA-256 hash of the User-Agent header (for audit; never the raw value). */
  user_agent_hash: NullableCol<string>;
  /** Free-form audit metadata. */
  metadata: Generated<Record<string, unknown>>;
}

/** Full row shape returned by SELECT queries on `consent_records`. */
export type ConsentRecord = Selectable<ConsentRecordsTable>;
/** Shape accepted by INSERT queries on `consent_records`. */
export type NewConsentRecord = Insertable<ConsentRecordsTable>;

// ---------------------------------------------------------------------------
// data_retention_preferences (000002_identity_preferences.sql — §7.7)
// ---------------------------------------------------------------------------

/**
 * Per-user data retention configuration.
 * One row per user; `user_id` is both the primary key and FK to `users`.
 *
 * raw_payload_retention_mode / ai_context_retention_mode allowed values:
 *   'extended' | 'standard' | 'minimal'
 */
export interface DataRetentionPreferencesTable {
  /** PK and FK to `users.id` (1-to-1 relationship). */
  user_id: string;
  /**
   * Raw provider payload retention policy.
   * Allowed: 'extended' | 'standard' | 'minimal'
   */
  raw_payload_retention_mode: Generated<string>;
  /**
   * Explicit retention window in days; null means policy-based (mode-driven).
   */
  raw_payload_retention_days: NullableCol<number>;
  /** Normalized/relational data retention policy. Default 'keep_until_deleted'. */
  normalized_data_retention_mode: Generated<string>;
  /**
   * AI context/snapshot retention policy.
   * Allowed: 'extended' | 'standard' | 'minimal'
   */
  ai_context_retention_mode: Generated<string>;
  /** Whether the algorithm engine may reprocess this user's data. */
  allow_algorithm_reprocessing: Generated<boolean>;
  updated_at: UpdatedAt;
}

/** Full row shape returned by SELECT queries on `data_retention_preferences`. */
export type DataRetentionPreferences = Selectable<DataRetentionPreferencesTable>;
/** Shape accepted by INSERT queries on `data_retention_preferences`. */
export type NewDataRetentionPreferences = Insertable<DataRetentionPreferencesTable>;
/** Shape accepted by UPDATE queries on `data_retention_preferences`. */
export type DataRetentionPreferencesUpdate = Updateable<DataRetentionPreferencesTable>;

// ---------------------------------------------------------------------------
// Database interface
// ---------------------------------------------------------------------------

/**
 * The root Kysely `Database` interface mapping table names to their row types.
 *
 * Pass this as the generic parameter when constructing the Kysely instance:
 *
 * ```typescript
 * import { Kysely } from 'kysely';
 * import type { Database } from './types.js';
 *
 * const db = new Kysely<Database>({ dialect });
 * ```
 *
 * The `schema_migrations` table is included so the migration runner can perform
 * type-safe inserts and selects when tracking applied migration versions.
 */
export interface Database {
  schema_migrations: SchemaMigrationsTable;

  // CU-027: Identity, preferences, and consent
  users: UsersTable;
  auth_identities: AuthIdentitiesTable;
  user_goals: UserGoalsTable;
  coach_preferences: CoachPreferencesTable;
  nutrition_philosophy_preferences: NutritionPhilosophyPreferencesTable;
  consent_records: ConsentRecordsTable;
  data_retention_preferences: DataRetentionPreferencesTable;
}

// Re-export Generated and Kysely DML helpers for use in table definitions added by later CUs.
export type { Generated, Selectable, Insertable, Updateable };
